services:
  app:
    build: .
    container_name: api_turnos
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:tu_pass_db@db:5432/turnos_db
      RABBITMQ_URL: amqp://guest:guest@broker:5672/

      KEYCLOAK_URL: http://localhost:8080/realms/turnos_realm

      KEYCLOAK_INTERNAL_URL: http://keycloak:8080/realms/turnos_realm

      KEYCLOAK_CLIENT_ID: turnos_app
      OTEL_SERVICE_NAME: "sistema-turnos-api"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318/v1/traces"
    volumes:
      - .:/app
    networks:
      - turnos_net
    depends_on:
      - db
      - broker
      - keycloak

  # --- 2. Worker (Consumidor) ---
  worker:
    build: .
    container_name: worker_turnos
    command: python -m app.worker
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:tu_pass_db@db:5432/turnos_db
      RABBITMQ_URL: amqp://guest:guest@broker:5672/
      OTEL_SERVICE_NAME: "sistema-turnos-worker"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318/v1/traces"
    volumes:
      - .:/app
    networks:
      - turnos_net
    depends_on:
      - broker
      - db

  # --- 3. Base de Datos (Negocio) ---
  db:
    image: postgres:16-alpine
    container_name: db_turnos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_pass_db
      POSTGRES_DB: turnos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - turnos_net

  # --- 4. Base de Datos (Keycloak) ---
  keycloak_db:
    image: postgres:16-alpine
    container_name: db_keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - turnos_net

  # --- 5. Keycloak ---
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: iam_turnos
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
    networks:
      - turnos_net
    volumes:
      - ./config/keycloak/realm-export.json:/opt/keycloak/data/import/realm.json

  # --- 6. Broker RabbitMQ ---
  broker:
    image: rabbitmq:3-management-alpine
    container_name: broker_turnos
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - turnos_net

  # --- 7. PgAdmin ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_turnos
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@dominio.com"
      PGADMIN_DEFAULT_PASSWORD: "admin_password"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - turnos_net

  # --- 8. JAEGER (Trazas) ---
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger_turnos
    ports:
      - "16686:16686" # UI Web de Jaeger
      - "4317:4317" # Puerto OTLP gRPC
      - "4318:4318" # Puerto OTLP HTTP
    networks:
      - turnos_net

  # --- 9. PROMETHEUS (Métricas) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_turnos
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - turnos_net

  # --- 10. GRAFANA (Dashboard) ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_turnos
    ports:
      - "3000:3000"
    networks:
      - turnos_net
    depends_on:
      - prometheus
    volumes:
      # 1. Cargar la conexión a Prometheus
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      # 2. Cargar la configuración de Dashboards
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # 3. Cargar el archivo JSON del Dashboard
      - ./config/grafana/dashboards_json:/var/lib/grafana/dashboards

  # --- 11. Servidor de Email (Simulado) ---
  mailpit:
    image: axllent/mailpit
    container_name: mail_server
    ports:
      - "8025:8025" # Interfaz Web (Tu Gmail local)
      - "1025:1025" # Puerto SMTP (Donde el Worker manda el mail)
    networks:
      - turnos_net

volumes:
  postgres_data:
  keycloak_postgres_data:
  rabbitmq_data:
  pgadmin_data:

networks:
  turnos_net:
    driver: bridge
